spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: create
#      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: real
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    open-in-view: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: true